language: php
php:
  - 5.4
  #- 5.5
  #- 5.6
  #- nightly

before_script:
  - composer self-update
  - composer install --dev
  - composer require magento-ecg/coding-standard
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - sed -i 's/file_exists/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - sed -i 's/file_get_contents/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - sed -i 's/filemtime/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - sed -i 's/is_writable/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - sed -i 's/is_readable/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - sed -i 's/exec/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - sed -i 's/imagecreatefrom/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php
  - sed -i 's/imagewebp/foobar/g' vendor/magento-ecg/coding-standard/Ecg/Sniffs/Security/ForbiddenFunctionSniff.php

script:
  - phpcs --standard=vendor/magento-ecg/coding-standard/Ecg -sv --encoding=utf-8 ./source
