language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - composer install --dev
  - pyrus install -f pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - vendor/bin/phpcs --standard=./phpcs.xml -sv --encoding=utf-8 ./source
