language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly

before_script:
  - composer self-update
  - composer install --dev
  - composer require magento-ecg/coding-standard
  - pyrus install -f pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=./vendor/magento-ecg/coding-standard -sv --encoding=utf-8 ./source
